export const ListOfProjects = [
	{id:1, video: "videos/RickAndMortyAngular.mp4", name: "RickAndMorty(Angular, SPA)", description: "Proyecto con funcionalidades de búsqueda, favoritos, notificaciones y lazy loading usando Angular, GraphQL y la API de rick y morty(rickandmortyapi.com)", code: "https://github.com/JohanSP721/AngularRickAndMorty.git"},
	{id:2, video: "videos/ClonWikipedia.mp4", name: "'Clon' de Wikipedia", description: "Un clon(visual) de la antigua pagina principal de  Wikipedia hecho con HTML5 y CSS puro", code: "https://github.com/JohanSP721/ClonWikipedia.git"},
	{id:3, video: "videos/RickAndMortyJS.mp4", name: "RickAndMorty(JS vanilla, SPA)", description: "Pagina SPA usando JavaScript puro, manejo de rutas con un router básico, CSS y HTML(dentro de javascript)", code:"https://github.com/JohanSP721/SPA.git"},
	{id:4, video: "videos/ReactPlatziStore.mp4", name: "ReactPlatziStore(SPA)", description: "Ejemplo de una tienda en linea (SPA) usando React(Hooks) y ReactRouter", code:"https://github.com/JohanSP721/ReactPlatziStore.git"},
	{id:5, video: "videos/ReactPlatziVideo.mp4", name: "ReactPlatziVideo(SPA)", description: "Proyecto con funcionalidades de búsqueda, animaciones, favoritos, reproductor de video, registro y login básicos, usando React(Hooks), ReactRouter y Redux para manejo de estado", code:"https://github.com/JohanSP721/ReactPlatziVideo.git"},
	{id:6, video: "videos/ToDosReact.mp4", name: "ToDosReact", description: "Proyecto con un CRUD básico de 'tareas' usando el local storage del navegador y React(Hooks)", code:"https://github.com/JohanSP721/ToDosReact.git"},
	{id:7, video: "videos/", name: "Portafolio(SPA)", description: "Portafolio de proyectos usando React(Hooks) y ReactRouter", code:"https://github.com/JohanSP721/Portafolio.git"},
	{id:8, video: "videos/Proyectos.mp4", name: "Proyectos(Repositorio)", description: "Repositorio de código con retos de programación en distintos lenguajes, algunos proyectos de FreeCodeCamp, retos y proyectos del programa misión tic 2022, proyectos de cursos de platzi y proyectos propios desarrollados de manera autodidacta", code:"https://github.com/JohanSP721/Proyectos.git"}
];
